language: node_js
cache:
  directories:
    - ~/.npm

node_js:
  - "lts/*"

branches:
  only:
    - master

before_install:
  - npm install -g npm@5

before_script:
  - npm prune

script:
  - npx sync-glitch-cli

notifications:
  email:
    on_failure: always